[package]
name = "iceberg-poc"
version = "0.1.0"
edition = "2021"

[dependencies]
iceberg = "0.4.0"
iceberg-catalog-rest = "0.4.0"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
futures = "0.3.31"
parquet = "53.4.0"
arrow-array = "53.4.0"
arrow-schema = "53.4.0"
